protocol_version: "v1.0.0"
# device id is unique to each device and is used on the cloud
device_id: "uid8933674633"
access_point_ssid: "RPiEdge"
access_point_password: none
edge_device_address: "192.168.4.1"
edge_device_port: "8009"
# The communication medium can be either bluetooth or wifi
communication_medium: "wifi"
 # Seconds between each message
transmission_rate: 10

 # flag for keeping the connection open with edge device
keep_alive: true

 # sensors contains a list of sensors that are connected to the device.
 # The order of the readings in a message will be the top down order of
 # all of the "values" in this file.
sensors:
  -
    # The path is the sensor path, the end device can read
    # and write to it in order to communicate with the sensor
    name: "spec_no2_sensor"
    path: "/dev/ttyUSB0"
    # values contain all the different attributes a sensor captures.
    # The value of each attribute is the number of bytes the device
    # will use to send the reading.
    values:
      - co: int
      - no2: short
  -
    name: "spec_co_sensor"
    path: "/dev/ttyUSB0"
    values:
      - humidity: float
      - temperature: short